apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "galaxy-k8s-monitor.fullname" . }}
data:
  namespace: {{ .Values.monitor.namespace | quote }}
  intervalSeconds: {{ .Values.monitor.intervalSeconds | quote }}
  retentionHours: {{ .Values.monitor.retentionHours | quote }}
  basePath: {{ .Values.monitor.basePath | quote }}
